name: lint-flake8

on: 
  push:
    branches:
    - '**'
  pull_request:

env: 
  POETRY_VIRTUALENVS_CREATE: "false"
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Python Poetry
      uses: abatilo/actions-poetry@v2.1.0
      with:
        poetry-version: 1.1.7
    - name: Install dependencies
      run: |
        python3 -m poetry install
    - name: Formatting the code with black
      run: |
        black --check comeAgainQuestionMark/
    - name: Lint the code with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 comeAgainQuestionMark/ --show-source --statistics
