name: pytest

on: [push, pull_request]
env: 
  POETRY_VIRTUALENVS_CREATE: "false"
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Python Poetry
      uses: abatilo/actions-poetry@v2.1.0
      with:
        poetry-version: 1.1.7
    - name: Install ffmpeg
      run: |
        sudo apt install ffmpeg
    - name: Install python dependencies
      run: |
        python3 -m poetry install
    - name: Run tests
      run: |
        pytest -s .
